name: converse_chat_core
description: Core logic and data models for the Converse Chat SDK.
version: 1.0.0
repository: https://github.com/rbishtdev/converse_chat_sdk/tree/main/packages/converse_chat_core
issue_tracker: https://github.com/yourusername/converse_chat_sdk/issues
homepage: https://github.com/rbishtdev/converse_chat_sdk
topics:
  - chat
  - sdk
  - flutter
  - core
  - firebase-chat

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  fpdart: ^1.1.1
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: Converse Chat Core architecture overview
    path: screenshots/architecture.png

flutter:
# No assets or fonts yet; can be added later
