name: converse_chat_adapters
description: Firebase-based infrastructure layer for the Converse Chat SDK. Implements repository interfaces from converse_chat_core for chat, user, presence, typing and  attachment management.
version: 1.0.1
repository: https://github.com/rbishtdev/converse_flutter_chat_sdk/tree/main/packages/converse_chat_adapters
issue_tracker: https://github.com/rbishtdev/converse_flutter_chat_sdk/issues
homepage: https://github.com/rbishtdev/converse_flutter_chat_sdk
topics:
  - chat
  - sdk
  - flutter
  - firebase
  - adapters

environment:
  sdk: ^3.7.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  converse_chat_core: ^1.0.0

  # Firebase SDKs
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_database: ^12.0.3

  fpdart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
