// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4PYMIimQsL4Y5fdcdZBwlWxHNcRLDSYY',
    appId: '1:111128872561:web:1a4c41f750e9e03c77bdd0',
    messagingSenderId: '111128872561',
    projectId: 'chat-app-6a40a',
    authDomain: 'chat-app-6a40a.firebaseapp.com',
    storageBucket: 'chat-app-6a40a.firebasestorage.app',
    measurementId: 'G-P1K7RTD07H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWYk1O-dGo1mYov8tLfUdLlR2AVHmOvf0',
    appId: '1:111128872561:android:d9e35bb64de8ae0b77bdd0',
    messagingSenderId: '111128872561',
    projectId: 'chat-app-6a40a',
    storageBucket: 'chat-app-6a40a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXOEqfoQPNmILHQxAg3-VMV-dzRDOywNI',
    appId: '1:111128872561:ios:31c80c364f55aaf577bdd0',
    messagingSenderId: '111128872561',
    projectId: 'chat-app-6a40a',
    storageBucket: 'chat-app-6a40a.firebasestorage.app',
    iosBundleId: 'com.converse.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXOEqfoQPNmILHQxAg3-VMV-dzRDOywNI',
    appId: '1:111128872561:ios:31c80c364f55aaf577bdd0',
    messagingSenderId: '111128872561',
    projectId: 'chat-app-6a40a',
    storageBucket: 'chat-app-6a40a.firebasestorage.app',
    iosBundleId: 'com.converse.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4PYMIimQsL4Y5fdcdZBwlWxHNcRLDSYY',
    appId: '1:111128872561:web:8d8014cd42c3ee0e77bdd0',
    messagingSenderId: '111128872561',
    projectId: 'chat-app-6a40a',
    authDomain: 'chat-app-6a40a.firebaseapp.com',
    storageBucket: 'chat-app-6a40a.firebasestorage.app',
    measurementId: 'G-5EZT4EYYQ8',
  );
}
